baseURL = 'https://xavierleune.tech/'
languageCode = 'fr-FR'
title = 'Blog personnel de Xavier Leune'
theme = 'anatole'

[params]
title = "Blog de Xavier Leune"
author = "Xavier Leune"
description = "PHP et affinités"
profilePicture = "images/profile.jpg"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/xleune/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/xavierleune"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://github.com/beoneself"

[[params.socialIcons]]
icon = "fa fa-file-pdf"
title = "CV"
url = "/2023-CV-Xavier-Leune-ano.pdf"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Veille"
  weight = 200
  identifier = "veille"
  url = "/veille/"

  [[menu.main]]
  name = "Talks"
  weight = 250
  identifier = "talks"
  url = "/talks/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
  
[services]
  [services.googleAnalytics]
    ID = 'G-9Z8ZMTJR6Q'