baseURL = 'https://xavierleune.tech/'
languageCode = 'fr-FR'
defaultContentLanguage = 'fr'
title = 'Blog personnel de Xavier Leune'
theme = 'anatole'

[params]
title = "Blog de Xavier Leune"
author = "Xavier Leune"
description = "PHP et affinités"
profilePicture = "images/profile.jpg"
customJs = ["js/analytics.js"]

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/xleune/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/xavierleune"

[[params.socialIcons]]
icon = "fa fa-globe"
title = "Alke Analytics: analytics built for publishers"
url = "https://www.alketech.eu"

[[params.socialIcons]]
icon = "fab fa-bluesky"
title = "Xavier Leune on Bluesky"
url = "https://bsky.app/profile/beoneself.bsky.social"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Veille"
  weight = 200
  identifier = "veille"
  url = "/veille/"

  [[menu.main]]
  name = "Talks"
  weight = 250
  identifier = "talks"
  url = "/talks/"

  [[menu.main]]
  name = "À propos de moi"
  weight = 300
  identifier = "about"
  url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"